//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutrijaWpfEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class komitenti_ime_matbr_zracun
    {
        public string IME { get; set; }
        public string PREZIME { get; set; }
        public string MATICNI_BROJ { get; set; }
        public string ZIRO_RACUN { get; set; }
        public string STARA_SIFRA { get; set; }
    }
}
